nelmio_api_doc:
    documentation:
        info:
            title: Yook Project
            description: Technical project for Carbon Offset
            version: 2.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
