app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

carbon-offsets:
    path: /api/offsets
    controller: App\Controller\Api\CarbonOffsetController::carbonOffsetsAction

carbon-offsets-by-year:
    path: /api/offsets/{year}
    controller: App\Controller\Api\CarbonOffsetController::carbonOffsetsByYearAction

price-offsets:
    path: /api/price-offsets/{year}/{price}
    controller: App\Controller\Api\CarbonOffsetController::carbonOffsetsByYearAction
