version: "3.8"

services:
  server:
    volumes:
      - ./server/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./server/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

  php:
    volumes:
      - ../../yook-project:/var/www/current

  database:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
