version: "3.8"

services:
  server:
    build:
      dockerfile: server/Dockerfile
      context: .
    volumes:
      - ../:/var/www/current/
    ports:
      - 80:80

  php:
    build:
      dockerfile: php/Dockerfile
      context: .
    volumes:
      - ../:/var/www/current

  database:
    build:
      dockerfile: database/Dockerfile
      context: .
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-db_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-db_password}
      POSTGRES_DB: ${DATABASE_NAME:-db_name}


    